#ifndef TINF_LINEAR_SOLVER_CONSTANTS_H
#define TINF_LINEAR_SOLVER_CONSTANTS_H

#define IPAR_LENGTH (16)
#define DPAR_LENGTH (16)


/* Indices to ipar */
#define RCI_INDEX (0)
#define PRECOND_DIRECTION_INDEX (1)
#define STOPPING_CRITERIA_INDEX (2)
#define WORK_SPACE_SIZE_INDEX (3)
#define KRYLOV_SUBSPACE_SIZE_INDEX (4)
#define MAX_MATVEC_INDEX (5)
#define MATVEC_COUNT_INDEX (6)
#define MATVEC_INPUT_INDEX (7)
#define MATVEC_OUTPUT_INDEX (8)
#define INTERNAL_INDEX (9)
#define EXTERNAL_CONVERGENCE_TEST_INDEX (10)
#define ORTHOG_ERROR_INDEX (11)
#define INIT_COUNT_INDEX (12)
#define REORTH_INDEX (13)
#define ORTHOG_SELECTION_INDEX (14)
#define C_FORTRAN_INDEXING (15)

/* Indices to dpar */
#define RELATIVE_TOLERANCE_INDEX (0)
#define ABSOLUTE_TOLERANCE_INDEX (1)
#define INITIAL_RESIDUAL_INDEX (2)
#define TARGET_RESIDUAL_INDEX (3)
#define CURRENT_RESIDUAL_INDEX (4)
#define CURRENT_RESIDUAL_ERROR_INDEX (5)
#define CONVERGENCE_RATE_INDEX (6)
#define SOLVER_TIMER_INDEX (7)
#define FLOP_COUNT_INDEX (10)

/* RCI flags */
#define LINEAR_SOLVERCONVERGED (0)
#define LINEAR_SOLVERSTOPPED (-1)
#define USER_MATRIX_VECTOR_PRODUCT (1)
#define USER_TRANS_MATRIX_VECTOR_PRODUCT (2)
#define USER_LEFT_PRECONDITIONER_APPLICATION (3)
#define USER_LEFT_TRANS_PRECONDITIONER_APPLICATION (4)
#define USER_RIGHT_PRECONDITIONER_APPLICATION (5)
#define USER_RIGHT_TRANS_PRECONDITIONER_APPLICATION (6)
#define USER_STOPPING_TEST (10)
#define USER_RESTART (11)

#endif 
